url: https://24eme.fr
baseurl:

# Site settings
title: 24ème
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Mathurin PETIT
  pic: 1
  position: Associé (Gérant)
  social:
    - title: github
      url:
    - title: twitter
      url: #
    - title: linkedin
      url: #

- name: Jean-Baptiste LE METAYER
  pic: 2
  position: Associé (Gérant)
  social:
    - title: github
      url:
    - title: twitter
      url: #
    - title: linkedin
      url: #

- name: Vincent LAURENT
  pic: 3
  position: Associé (Gérant)
  social:
    - title: github
      url:
    - title: twitter
      url: #
    - title: linkedin
      url: #

- name: Tangui MORLIER
  pic: 4
  position: Associé
  social:
    - title: github
      url:
    - title: twitter
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/24emeSCOP
  - title: facebook
    url:
  - title: github
    url: http://github.com/24eme

# Postal address (add as many lines as necessary)
address:
  - line: 12 avenue de l'Amiral Mouchez
  - line: 75014 Paris

# Build settings
markdown: kramdown
permalink: pretty
