url: https://www.24eme.fr
baseurl: /

# Site settings
title: "24ème : Fabricant de logiciels"
email: contact[at]24eme.fr
description: "Conception et développement de logiciels libres adaptés aux métiers de nos clients"


# Team names, titles and social links
people:
- name: Mathurin PETIT
  pic: 1
  position: Associé (Gérant)
  social:
    - title: github
      url: https://github.com/mathurinpetit
    - title: twitter
      url: https://twitter.com/MathurinPetit
    - title: linkedin
      url: https://www.linkedin.com/in/mathurin-petit-69007a51/

- name: Jean-Baptiste LE METAYER
  pic: 2
  position: Associé (Gérant)
  social:
    - title: github
      url: https://github.com/jblemetayer
    - title: twitter
      url: https://twitter.com/jblemetayer
    - title: linkedin
      url: https://www.linkedin.com/in/jean-baptiste-le-metayer-ba4577103/

- name: Vincent LAURENT
  pic: 3
  position: Associé (Gérant)
  social:
    - title: github
      url: https://github.com/wincelau
    - title: twitter
      url: https://twitter.com/wincelaurent
    - title: linkedin
      url: https://www.linkedin.com/in/vincent-laurent-4966694b/

- name: Tangui MORLIER
  pic: 4
  position: Associé
  social:
    - title: github
      url: https://github.com/teymour
    - title: twitter
      url: https://twitter.com/teymour
    - title: linkedin
      url: https://www.linkedin.com/in/tanguimorlier/

- name: Gabriel POMA
  pic: 5
  position: Associé
  social:
    - title: github
      url: https://github.com/gpoma

- name: Moussa ADJI
  pic: 6
  position: Associé Alternant (développeur fullstack)
  social:
    - title: github
      url: https://github.com/2maj
    - title: linkedin
      url: https://fr.linkedin.com/in/moussa-adji-mahamat
    - title: instagram
      url: https://www.instagram.com/mht_adji/?hl=fr-ca

- name: Honorine MARIE-CHRISTY
  pic: 7
  position: Alternante (développeur fullstack)
  social:
    - title: github
      url: https://github.com/Honorine-MC
    - title: linkedin
      url: https://fr.linkedin.com/in/honorine-marie-christy
#    - title: instagram
#      url: https://www.instagram.com/mht_adji/?hl=fr-ca

- name: Mame-Diarra NGOM
  pic: 8
  position: Alternante (développeur fullstack)
  social:
    - title: github
      url: https://github.com/Mngom-ai
    - title: linkedin
      url: https://fr.linkedin.com/in/mamediarrangom

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/24eme
  - title: twitter
    url: http://twitter.com/24emeSCOP
  - title: linkedin
    url: https://www.linkedin.com/company/9437998
  - title: facebook
    url: https://www.facebook.com/24eme

# Postal address (add as many lines as necessary)
address:
  - line: 2 place Sainte-Opportune
  - line: 75001 Paris

# Build settings
markdown: kramdown
permalink: pretty
